algoritmo "Atividade 6 da apostila de LP"
// Função : Escreva um algoritmo para ler as dimensões de um retângulo (base e altura), calcular e escrever a  área do retângulo.
// Autor : Matheus Souza Parreiras
// Data : 07/03/2023
// Seção de Declarações 
var
base, altura, area: real
inicio
// Seção de Comandos
escreval("Digite a base")
leia(base)
escreval("Digite a altura")
leia(altura)
area := (base * altura)
escreval ("Área: ", area)
fimalgoritmo
