algoritmo "Atividade 14 da apostila de LP"
// Função : Ler um valor e escrever a mensagem É MAIOR QUE 10! se o valor lido for maior que 10, caso  contrário escrever NÃO É MAIOR QUE 10!
// Autor : Matheus Souza Parreiras
// Data : 08/03/2023
// Seção de Declarações 
var
V : real
inicio

leia(V)
se V > 10 entao
escreval("É maior que 10")
senao
escreval("Não é maior que 10")
fimse
// Seção de Comandos
fimalgoritmo

