algoritmo
// Função :
// Autor :
// Data : 08/03/2023
// Seção de Declarações 
var
N1, N2, media : real
inicio

escreval("Insira a primeira nota:")
leia(N1)
escreval("Insira a segunda nota:")
leia(N2)
media := (N1 + N2) / 2
se media >= 6 entao
escreval("Você foi aprovado! Sua média foi:", media)
senao
escreval("Você NÃO foi aprovado! Sua média foi:", media)
fimse
// Seção de Comandos
fimalgoritmo

