algoritmo "Atividade 2b) da Apostila LP"
// Função :
// Autor :
// Data : 08/03/2023
// Seção de Declarações 
var
a , b , c , aux: inteiro
inicio
escreval ("Valor de C")
a := 30
b := 20
c := (a + b)
aux := 10

escreval("C = ", c)

b := aux

escreval ("Valores de B e C")
escreval("B = ", b)
escreval("C = ", c)

c := (a + b)
escreval ("Valores atualizados")
escreval("A = ", a)
escreval("B = ", b)
escreval("C = ", c)

// Seção de Comandos 
fimalgoritmo
