algoritmo "Atividade 2c) da Apostila LP"
// Função : Analise os algoritmos abaixo e diga o que será impresso na tela ao serem executados - C)
// Autor : Matheus Souza Parreiras
// Data : 08/03/2023
// Seção de Declarações 
var
a , b , c , aux: inteiro
inicio
a := 10
b := 20
c := a
aux := c
b := c
a := b

escreval ("A = ", a)
escreval ("B = ", b)
escreval("C = ", c)

// Seção de Comandos 
fimalgoritmo
