algoritmo "Atividade 5 da apostila de lp"
// Função : Escreva um algoritmo para ler um valor (do teclado) e escrever (na tela) o seu antecessor.
// Autor : Matheus Souza Parreiras
// Data : 07/03/2023
// Seção de Declarações 
var
nota1, soma: real
inicio
// Seção de Comandos
escreval("Digite o número desejado")
leia(nota1)
soma := (nota1 - 1)
escreval ("O antecessor do número inserido é: ", soma)
fimalgoritmo
